### ISSUE TITLE
Create Property page

### ISSUE THREAD

**Issue by csocrate** [csocrate/Rental-properties-app-React#10]
**Description**
Create Property page with  its components and style sheet.

**Tasks**
- [x] Add Slideshow component
- [x] Add Collapse component
- [x] Styling Property component
