### ISSUE TITLE
Add features and code improvements

### ISSUE THREAD

**Issue by csocrate** [csocrate/Rental-properties-app-React#14]
**Description**

- Add features and code improvements.

**Tasks**
- [x] Remove Fetch API and use import instead of it | Home page
- [x] Remove styled component to use only one css file
- [x] Check style, HTML and update them if necessary
- [x] Update 404 page with conditional operator and Link
- [x] Clean code
- [x] Validate HTML and CSS files with W3C
