### ISSUE TITLE
Update Home page with components

### ISSUE THREAD

**Issue by csocrate** [csocrate/Rental-properties-app-React#6]
**Description**
Update Home page with  its components and style sheet.

**Tasks**
- [x] Add Banner component
- [x] Add Card component
- [x] Styling Home component
