### ISSUE TITLE
Update About page with components

### ISSUE THREAD

**Issue by csocrate** [csocrate/Rental-properties-app-React#8]
**Description**
Update About page with  its components and style sheet.

**Tasks**
- [x] Add Banner component
- [x] Add Collapse component
- [x] Styling About component
